server:
#  error:
#    whitelabel:
#      enabled: false
  context-path : /sts
  port : 8080
  tomcat:
    apr:
      enabled: true
  servlet:
    timeout : 900

spring:
#  mvc:
#    static-path-pattern: /resources/**
  thymeleaf:
    cache: false
    mode: HTML
    templates_root: sts-web/src/main/resources/templates/
  devtools:
    restart:
      enabled : true

logging:
  level:
    #    web : DEBUG
    com:
      wissensalt:
        rnd:
          slr:
            web:
              feign: DEBUG

api:
  base-path : http://localhost:8081